version: '3'
services:
  db:
    image: mysql:5.6
    container_name: 'caelum-mysql-casadocodigo'
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "casadocodigo"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d